name: ast366
channels:
  - astropy
dependencies:
- python=3.6
- astropy=1.3
- astroquery
- matplotlib
- ipython
- jupyter
- ipywidgets
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- wcsaxes
- astroplan
- pip:
  - msumastro==0.9.0

