name: ast366
channels:
  - astropy
  - conda-forge
dependencies:
- python=3.6
- astropy
- astroquery
- matplotlib
- ipython
- jupyter
- ipywidgets
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- wcsaxes
- astroplan
- msumastro
- reducer

