name: ast366
channels:
  - astropy
dependencies:
- python=3.5.1
- astropy=1.2.1
- astroquery
- matplotlib
- ipython
- jupyter
- ipywidgets=4*
- scipy
- nose
- mock
- funcsigs
- pillow
- ccdproc
- scikit-image
- dask
- pip:
  - msumastro==0.9.0
  - reducer==0.3.0
  - astroplan==0.1

